name = "book-hot"
description = ""
strategy = "PUBLIC"

[[params]]
name = "limit"
type = "int"
required = false
positional = false
description = "Number of books to return"
default = 20

[execution]
entry = "script"
script = "scripts/book-hot.json"

[output]
columns = []
