name = "bounties"
description = "Active bounties on Stack Overflow"
strategy = "PUBLIC"

[[params]]
name = "limit"
type = "int"
required = false
positional = false
description = "Max number of results"
default = 10

[execution]
entry = "script"
script = "scripts/bounties.json"

[output]
columns = ["bounty", "title", "score", "answers", "url"]
