name = "hot"
description = "Hot Stack Overflow questions"
strategy = "PUBLIC"

[[params]]
name = "limit"
type = "int"
required = false
positional = false
description = "Max number of results"
default = 10

[execution]
entry = "script"
script = "scripts/hot.json"

[output]
columns = ["title", "score", "answers", "url"]
