name = "notifications"
description = "即刻通知"
strategy = "COOKIE"

[[params]]
name = "limit"
type = "int"
required = false
positional = false
description = "Number of notifications"
default = 20

[execution]
entry = "script"
script = "scripts/notifications.json"

[output]
columns = ["type", "user", "content", "time"]
