name = "read"
description = ""
strategy = "COOKIE"

[[params]]
name = "subreddit"
type = "string"
required = false
positional = false
description = ""
default = "all"

[execution]
entry = "script"
script = "scripts/read.json"

[output]
columns = []
