name = "top"
description = ""
strategy = "PUBLIC"

[[params]]
name = "limit"
type = "int"
required = false
positional = false
description = "Number of stories to fetch"
default = 30

[execution]
entry = "script"
script = "scripts/top.json"

[output]
columns = ["title", "url", "score", "author"]
