name = "feed"
description = "Get your Facebook news feed"
strategy = "PUBLIC"

[[params]]
name = "limit"
type = "int"
required = false
positional = false
description = "Number of posts"
default = 10

[execution]
entry = "script"
script = "scripts/feed.json"

[output]
columns = ["index", "author", "content", "likes", "comments", "shares"]
