name = "notifications"
description = "Get recent Facebook notifications"
strategy = "PUBLIC"

[[params]]
name = "limit"
type = "int"
required = false
positional = false
description = "Number of notifications"
default = 15

[execution]
entry = "script"
script = "scripts/notifications.json"

[output]
columns = ["index", "text", "time"]
